### ISSUE TITLE
Running policr-macos with example files

### ISSUE THREAD

**Issue by thbaz** [LoooooKe/policr#20]
# policr Version
0.1.0

# command used 

/policr-macos -w ../tf -t ../examples  tf-plan

# Terraform Plan or Cloudformation

annexed 
[tf.zip](https://github.com/LoooooKe/policr/files/1471026/tf.zip)

# Test Files

The ones from examples 

# Crash Output

```
Child exited with code: 0
TypeError: Cannot read property 'all' of undefined
    at Suite.<anonymous> (/Users/thbas/hub.git/policr/examples/basic.js:7:28)
    at Object.create (/snapshot/policr/node_modules/mocha/lib/interfaces/common.js:112:19)
    at module.exports.suite.on.context.describe.context.context (/snapshot/policr/node_modules/mocha/lib/interfaces/bdd.js:44:27)
    at Object.<anonymous> (/Users/thbas/hub.git/policr/examples/basic.js:6:1)
    at Module._compile (module.js:573:30)
    at Module._compile (pkg/prelude/bootstrap.js:1187:32)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```
# Expected Behavior
policr results

# Actual Behavior
TypeError

# References

**Comment by LoooooKe** [comment]
This is due to refactoring towards the resorceMap. This is already fixed in 48542dff
